### ISSUE TITLE
New site to add: www.shijiexia.com

### ISSUE THREAD

**Issue by IBeiKui** [StopModReposts/Illegal-Mod-Sites#515] opened 2022-05-21 09:14 UTC
**What site do you want to be added?**
http://www.shijiexia.com/

**What game does the site repost content for?** (Example: Minecraft, Subnautica, etc)
Minecraft.

**Do you have anything else worth mentioning?**
This website not only provides direct file downloads but also copies descriptions from another website www.mcmod.cn without complying with the license "BY-NV-SA 3.0"(An example can be seen below).

https://www.curseforge.com/minecraft/mc-mods/wandering-bag - http://www.shijiexia.com/wanderingbag.html - https://www.mcmod.cn/class/6231.html

**Comment by dada513** [comment] 2022-05-21 18:39
Duplicate of #473

**Closed by dada513** 2022-05-21 18:39 UTC
Labels: addition, duplicate
