### ISSUE TITLE
Site removal: mcbbs.net

### ISSUE THREAD

**Issue by FeyXieXzf** [StopModReposts/Illegal-Mod-Sites#514] opened 2022-05-16 06:54 UTC
**What site do you want to be removed?** mcbbs.net

**Why?**
mcbbs.net is the biggest minecraft forum in China. Due to the "Great Fire Wall" in China blocking most of the websites from other countries, it makes it incredibly slow when accessing curseforge and modrinth (and possibly other sites) inside china. Also, i need to mention that most of the people reposting mods in mcbbs **have got the authorization from the mod author**, and most of them did not reupload the mod, instead they just provides a link to the original mod page. If they didn't do that and they reposts illegally, they are handled inside mcbbs.net.

**Comment by berrysauce** [comment] 2022-05-27 22:18
Duplicate of #513

**Closed** 2022-05-27 22:19 UTC
Labels: removal, duplicate

**Comment by GEOEGII555** [comment] 2022-07-21 09:15
> Your request was denied since the domain was already added or denied before. **Please do not open a new issue with the same domain again.**
> 
> > ℹ️ If you think this was an error, comment below and a project maintainer will review the request again.

This is wrong

**Comment by catbytrain** [comment] 2023-11-20 07:52
> > Your request was denied since the domain was already added or denied before. **Please do not open a new issue with the same domain again.**
> > > ℹ️ If you think this was an error, comment below and a project maintainer will review the request again.
> 
> This is wrong

reporanger is trying it's best to say it's a duplicate, cut it some slack.

**Comment by berrysauce** [comment] 2023-11-29 20:14
@GEOEGII555 
As of my knowledge, this site doesn't comply with our internal guidelines. You're still free to fill out the Removal Request form: https://tally.so/r/wMGOXm
